
stages:
  - convert
  - upload
  - delete
  - release
  
variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/latest"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" # only run this pipeline upon a schedule event
    
convert:
  stage: convert
  image: "python:3.10"
  script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install numpy scipy
    - python3 convert.py
  artifacts:
    paths:
      - data.zip
      - CHANGELOG.md

upload:
  stage: upload
  image: curlimages/curl:latest
  script:
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file data.zip "${PACKAGE_REGISTRY_URL}/data.zip"'

delete:
  stage: delete
  image: curlimages/curl:latest
  allow_failure: true
  script:
    - |
      echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/latest"
      curl --request DELETE --header "JOB-TOKEN: ${CI_JOB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/latest"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "Data" --tag-name "latest" --description "CHANGELOG.md" \
        --assets-link "{\"name\":\"data.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}/data.zip\"}"