DataLogger:
    backupCount: 70 # number of datalogs to keep
    filename: data # filename for datalogs
    levels: # log level for outputting to file and to stdout respectivly
        - INFO
        - WARNING

InfoLogger:
    backupCount: 10 # number of logs to keep
    maxBytes: 100000 # size of single log in bytes
    filename: log # filename for logs
    levels: # log level for outputting to file and to stdout respectivly
        - INFO
        - WARNING

Data:
    factors: [1.855, 0, 0.923, -1] # factors for the 4 dms
    delta_time: 10 # time between logging data
