DataLogger:
    backupCount: 350 # number of datalogs to keep
    levels: # log level for outputting to file and to stdout respectivly
        - INFO
        - WARNING

InfoLogger:
    backupCount: 10 # number of logs to keep
    maxBytes: 100000 # size of single log in bytes
    levels: # log level for outputting to file and to stdout respectivly
        - INFO
        - WARNING

Data:
    factors: [1.855, 0, 0.923, -1] # factors for the 4 dms
    delta_time: 30 # time between logging data
