name: Convert data to .mat file(s)

on:
  schedule:
      - cron: "0 1 * * 0,3"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install numpy scipy
    - name: Convert data
      run: |
        python3 convert.py
        cd out && zip ../data.zip ./* && cd -
        ls .
        ls ..
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: "Data"
        tag_name: latest
        body_path: ./CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload out artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./data.zip
        asset_name: data.zip
        asset_content_type: application/zip
        
